export const MOCK_GOLD_RATE = {
  price: 7250.50,
  change: 1.25,
  isUp: true,
  lastUpdated: 'Today, 10:30 AM',
};

export const MOCK_ACTIVE_SCHEMES = [
  {
    id: '1',
    name: 'Wedding Gold Savings',
    totalAmount: 120000,
    paidAmount: 45000,
    nextDueAmount: 5000,
    nextDueDate: '2026-06-05',
    progress: 0.375,
    monthsPaid: 9,
    totalMonths: 24,
    pendingInstallments: 1,
  },
];

export const MOCK_AVAILABLE_SCHEMES = [
  {
    id: 's1',
    title: 'Smart Gold Plan',
    monthlyAmount: 2000,
    duration: 11,
    bonus: '1 Month Installment Free',
    description: 'Save monthly and get 1 month installment as bonus at the end of the term.',
  },
  {
    id: 's2',
    title: 'Premium Gold Saver',
    monthlyAmount: 5000,
    duration: 12,
    bonus: '0.5% Extra Weight',
    description: 'Ideal for long term savings with guaranteed extra gold weight.',
  },
  {
    id: 's3',
    title: 'Flexi Gold Chit',
    monthlyAmount: 1000,
    duration: 10,
    bonus: 'No Making Charges',
    description: 'Flexible savings with zero making charges on jewelry purchase.',
  },
];

export const MOCK_PAYMENTS = [
  {
    id: 'p1',
    schemeName: 'Wedding Gold Savings',
    amount: 5000,
    date: '2026-05-01',
    status: 'Paid',
    transactionId: 'TXN123456789',
    installmentNo: 9,
    method: 'UPI',
  },
  {
    id: 'p2',
    schemeName: 'Wedding Gold Savings',
    amount: 5000,
    date: '2026-04-02',
    status: 'Paid',
    transactionId: 'TXN123456780',
    installmentNo: 8,
    method: 'Card',
  },
  {
    id: 'p3',
    schemeName: 'Wedding Gold Savings',
    amount: 5000,
    date: '2026-03-05',
    status: 'Paid',
    transactionId: 'TXN123456781',
    installmentNo: 7,
    method: 'Net Banking',
  },
  {
    id: 'p4',
    schemeName: 'Wedding Gold Savings',
    amount: 5000,
    date: '2026-02-05',
    status: 'Paid',
    transactionId: 'TXN123456782',
    installmentNo: 6,
    method: 'UPI',
  },
  {
    id: 'p5',
    schemeName: 'Wedding Gold Savings',
    amount: 5000,
    date: '2026-01-05',
    status: 'Failed',
    transactionId: 'TXN123456783',
    installmentNo: 5,
    method: 'UPI',
  },
  {
    id: 'p6',
    schemeName: 'Wedding Gold Savings',
    amount: 5000,
    date: '2026-01-07',
    status: 'Paid',
    transactionId: 'TXN123456784',
    installmentNo: 5,
    method: 'Card',
  },
  {
    id: 'p7',
    schemeName: 'Wedding Gold Savings',
    amount: 5000,
    date: '2025-12-05',
    status: 'Paid',
    transactionId: 'TXN123456785',
    installmentNo: 4,
    method: 'UPI',
  },
  {
    id: 'p8',
    schemeName: 'Wedding Gold Savings',
    amount: 5000,
    date: '2025-11-05',
    status: 'Paid',
    transactionId: 'TXN123456786',
    installmentNo: 3,
    method: 'UPI',
  },
  {
    id: 'p9',
    schemeName: 'Wedding Gold Savings',
    amount: 5000,
    date: '2025-10-05',
    status: 'Paid',
    transactionId: 'TXN123456787',
    installmentNo: 2,
    method: 'UPI',
  },
  {
    id: 'p10',
    schemeName: 'Wedding Gold Savings',
    amount: 5000,
    date: '2025-09-05',
    status: 'Paid',
    transactionId: 'TXN123456788',
    installmentNo: 1,
    method: 'UPI',
  },
];

export const MOCK_OFFERS = [
  {
    id: 'o1',
    title: 'Akshaya Tritiya Special',
    description: 'Get 0.5% extra gold on new scheme enrollment.',
    validity: 'Valid till 20th May',
    bonus: '0.5%',
    type: 'Festival',
    image: 'https://images.unsplash.com/photo-1589118949245-7d38baf380d6?w=800&auto=format&fit=crop&q=60',
  },
  {
    id: 'o2',
    title: 'Refer & Earn',
    description: 'Refer a friend and get ₹500 gold bonus.',
    validity: 'Limited Time',
    bonus: '₹500',
    type: 'Referral',
    image: 'https://images.unsplash.com/photo-1579621970563-ebec7560ff3e?w=800&auto=format&fit=crop&q=60',
  },
  {
    id: 'o3',
    title: 'Welcome Bonus',
    description: 'Join any premium scheme and get 1st month 10% off.',
    validity: 'New Users Only',
    bonus: '10% OFF',
    type: 'Featured',
    image: 'https://images.unsplash.com/photo-1610375461246-83df859d849d?w=800&auto=format&fit=crop&q=60',
  },
];
